### ISSUE TITLE
Review Mobile Layout

### ISSUE THREAD

**Issue by ScharV** [hoobs-org/gui#1] opened 2021-03-02 19:09 UTC
1. Weather information block on Dashboard is cutted

2. Every window, like settings or plugin installation configuration, which shows up on the right side of the screen is only visible if you know this behavior and scroll to the right side.

**Comment by mkellsy** [comment] 2021-03-02 20:15
Need a medium responsive section for ipads

**Comment by mkellsy** [comment] 2021-03-05 02:21
Duplicate of #2

**Closed as completed by mkellsy** 2021-03-05 02:21 UTC
